/**
 * Suggested track comments for the download gate.
 *
 * Modeled on real SoundCloud comment sections: mostly 1–4 words, lowercase,
 * stretched letters, sparse emoji. The gate
 * pre-fills one at random and the fan can edit, re-roll, or switch it off —
 * they always see exactly what will post under their name.
 */
export const COMMENT_POOL = [
  "diabolical",
  "straight slime",
  "beyond gas",
  "holy",
  "actually cracked",
  "wowww🤯",
  "yooo this is insane",
  "this intro omg",
  "this goes insane",
  "legend",
  "my god",
  "insaaane",
  "im all earz",
  "im listening",
  "im listeninnnn!!!",
  "blessing my ears again",
  "this is so hard wtf",
  "fresh",
  "this is nuts",
  "crazyyyy",
  "crazy",
  "well i'll be",
  "nasty work",
  "so nasty omg",
  "big af !",
  "🔥 woow",
  "yoo",
  "yuh",
  "damnnn",
  "oh my days",
  "yeee 🔥",
  "🐐",
  "listen ‼️🗣",
  "👂🦻",
  "fucking hell",
  "!!!!!",
  "another crazy tune",
  "bro doesn't miss",
  "hes goated",
  "that's disrespectful",
  "wtfff",
  "yuhhh",
  "massive :o",
  "im listening!",
  "oh… my… god",
  "absolutely insane chune",
  "the drop??? hello???",
  "sheeeesh",
  "no way this is free",
  "free?? ur insane",
  "ripping this in my sets",
  "cant wait to play this out",
  "rewind button broken now",
  "on loop fr",
  "certified heat",
  "gas ⛽",
  "this slaps silly",
  "down bad for this one",
  "ok this hits",
  "bruh 💀",
  "unreal",
  "stoppp this is too good",
  "why is this so good",
  "how",
  "how even",
  "nah this crazy",
  "nahhh 😭",
  "cooked",
  "he cooked",
  "chef mode",
  "W",
  "massive W",
  "banger alert 🚨",
  "tune 🔥",
  "chuneee",
  "goosebumps fr",
  "chills chills chills",
  "ears blessed 🙏",
  "speakers crying rn",
  "volume maxed",
  "neighbors mad, worth it",
  "aux ready",
  "festival weapon",
  "main stage energy",
  "id request??",
  "what do you eat fr",
  "teach me pls",
  "vicious",
  "filthy",
  "filthyyy 🤢",
  "disgusting (good)",
  "evil drop 😈",
  "menace behavior",
  "straight venom",
  "hardest thing i heard today",
  "10/10 no notes",
  "run it back",
  "the whole thing is a highlight",
  "cant believe my ears rn",
  "up there with the greats"
];

/** Uniform random pick; pass the current value to guarantee a re-roll differs. */
export const randomComment = (avoid?: string) => {
  let pick = COMMENT_POOL[Math.floor(Math.random() * COMMENT_POOL.length)];
  while (COMMENT_POOL.length > 1 && pick === avoid) {
    pick = COMMENT_POOL[Math.floor(Math.random() * COMMENT_POOL.length)];
  }
  return pick;
};
